# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0002_auto_20170712_2052'),
        ('bank', '0002_auto_20170712_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('balance', models.DecimalField(
                    decimal_places=2,
                    max_digits=12
                )),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bank', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='accounts',
                    to='bank.Bank'
                )),
                ('currency', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='bank_accounts',
                    to='exchange.Currency'
                )),
            ],
            options={
                'db_table': 'bank_account',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set([('bank', 'name', 'currency')]),
        ),
    ]
