# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20170716_1809'),
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set([('bank', 'name')]),
        ),
    ]
