# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20170712_2052'),
        ('bank', '0002_auto_20170712_2052'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('bank', 'name', 'currency')]),
        ),
    ]
