
#branches:
#  only:
#  - master
#  - development

language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres

script:
  - flake8 .
  - ./manage.py migrate
  - ./manage.py test

notifications:
  email:
    on_success: never
    on_failure: always
