# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_conversion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
