# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'expense_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('amount', models.DecimalField(
                    decimal_places=2,
                    max_digits=12
                )),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='expenses',
                    to='expense.Category'
                )),
                ('currency', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='expenses',
                    to='exchange.Currency'
                )),
            ],
            options={
                'db_table': 'expense',
                'ordering': ['date'],
            },
        ),
    ]
