# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20170712_2052'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ExpenseCategory',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='expense_category',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expense_categories',
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together=set([('user', 'name')]),
        ),
    ]
