# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_auto_20170730_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(
                help_text='A category of expenses (e.g. "Food", '
                          '"Housing", etc).',
                max_length=255
            ),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='order',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='An order this category will be displayed '
                          'among other categories'
            ),
        ),
    ]
