# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
