# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_auto_20170730_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesource',
            name='name',
            field=models.CharField(
                help_text='An income source (e.g. "Salary", "Gifts", etc).',
                max_length=255
            ),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='order',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='An order this income source will be displayed '
                          'among the other ones'
            ),
        ),
    ]
